set nocompatible
set encoding=utf-8
set number
set noerrorbells
set novisualbell
set backspace=indent,eol,start
set autoindent
set nobackup
set foldmethod=marker

"Vundle config {{{1

filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

" Plugins
Plugin 'davidhalter/jedi-vim'
Plugin 'scrooloose/syntastic'
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'bling/vim-airline'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'

" javascript support
Plugin 'pangloss/vim-javascript'
let g:javascript_conceal_function="ƒ"

" Haskell support
"Plugin 'eagletmt/neco-ghc'

" Color schemes
Plugin 'flazz/vim-colorschemes'

call vundle#end()
filetype plugin indent on

"}}}

syntax on
colorscheme codeschool

" Airline fix
set laststatus=2

let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
let g:UltiSnipsEditSplit="vertical"


"Wildmenu options {{{1
set wildmenu
set wildignore=*.pyc,*.pyo,*.bak,*.png,*.jpg,*.gif,*.dll,*.o,*.exe,*.obj
set wildmode=full
"}}}

" My mappings {{{1
let mapleader = ","

nmap <leader>l :set list!<CR>
nmap <leader>n :bp<CR>
nmap <leader>m :bN<CR>
nmap <leader>w :w<CR>

inoremap <C-Space> <C-x><C-o>
inoremap <C-@> <C-Space>

"}}}

" MiniBufExplorer options {{{1
let g:miniBufExplMapCTabSwitchBufs = 1 
"}}}

" Autocommands {{{1
if has("autocmd")
   
  autocmd FileType make setlocal ts=8 sts=8 sw=8 noexpandtab
  autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
  autocmd FileType python setlocal tabstop=8 expandtab shiftwidth=4 softtabstop=4
  autocmd FileType html setlocal ts=2 sts=2 sw=2 expandtab
  autocmd FileType css setlocal ts=2 sts=2 sw=2 expandtab
  autocmd FileType javascript setlocal ts=4 sts=4 sw=4 noexpandtab
  autocmd BufNewFile,BufRead *.rss set filetype=xml
  autocmd BufNewFile,BufReadPost *.md set filetype=markdown
  autocmd FileType haskell set omnifunc=necoghc#omnifunc

endif
"}}}

" GUI options {{{1
if has("gui")

set guifont=Ubuntu\ Mono\ Regular\ 10

if has("gui_macvim")
set guifont=Menlo:h12
colorscheme railscasts
imap § <Esc>
map § <Esc>
endif


if has("win32")
colorscheme codeschool
behave mswin
set bs=2
endif

endif
"}}}

" Disable arrow keys - antipattern {{{1
noremap <Up> <nop>
noremap <Down> <nop>
noremap <Left> <nop>
noremap <Right> <nop>
"}}}

