# Plays the pronunciation and prints the mnemonics and definitions for a word
function define {
	(echo -e "Phoneme mnemonics: $(espeak -ven-uk-rp -x -s 120 "$1" 2> /dev/null)\n"; dict "$1") | less
}

# Load z if present
z=~/.local/bin/z.sh
if [ -f $z ]; then
	. $z
fi

function del_blackholes {
	sudo ip route list | grep blackhole | while read l; do sudo ip route del $l; done
}
