# Using restrictive umask, make sure that following sudo defaults are configured:
# Defaults umask = 0022
# Defaults umask_override
umask 0077

# Plays the pronunciation and prints the mnemonics and definitions for a word
function define {
	(echo -e "Phoneme mnemonics: $(espeak -ven-uk-rp -x -s 120 "$1" 2> /dev/null)\n"; dict "$1") | less
}

# Load autojump if present
autojump=/usr/share/autojump/autojump.sh
if [ -f $autojump ]; then
	. $autojump
fi

# Load bash-git-prompt if present
gitprompt=~/.bash-git-prompt/gitprompt.sh
if [ -f $gitpropmt ]; then
	. $gitprompt
	GIT_PROMPT_ONLY_IN_REPO=1
	GIT_PROMPT_THEME=Default_Ubuntu
fi
